# Generated by Django 5.2.7 on 2025-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postannouncement_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postannouncement',
            name='link_forms',
            field=models.URLField(blank=True, null=True),
        ),
    ]
