# Generated by Django 5.2.7 on 2025-12-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeed',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='feed/'),
        ),
    ]
